services:
  api:
    build: ./src/api/    
    image: mmmhdp/farseer_api:v0
    ports:
      - "8000:8000" 
    env_file:
       ./src/api/.prod.env
    depends_on:
      - fsm-stenographer
      - redis
      - kafka
    profiles: ["api"]

  fsm-stenographer:
    build: ./src/fsm_stenographer/    
    image: mmmhdp/farseer_fsm_stenographer:v0
    ports:
      - "5555:5555" 
    env_file:
       ./src/fsm_stenographer/.prod.env
    depends_on:
      - postgres
      - kafka
    profiles: ["fsm-st"]

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_PASSWORD=Qq220605
      - POSTGRES_USER=nikita
      - POSTGRES_DB=crud_db 
      - PGDATABASE=crud_db
    profiles: ["infr"]

  redis:
    image: redis
    ports:
      - "6379:6379"
    profiles: ["infr"]
    
  
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    profiles: ["infr"]
  
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    profiles: ["infr"]
